/*!
 * @author      Yash Bansod
 * @date        17th September 2017
 *
 * @brief       Blink with delay
 * @details     The program controls the RGB LEDs on the Tiva C board
 *              TM4C123G LaunchPad (with TM4C123GH6PM microcontroller) and
 *              blinks the Blue, Green and Red Led with a specified delay.
 *              The Delay is generated by wasting machine cycles in a loop.
 */

/* -----------------------          Include Files       --------------------- */

#include <stdint.h>                     // Library of Standard Integer Types
#include <stdbool.h>                    // Library of Standard Boolean Types
#include "inc/hw_memmap.h"              // Macros defining the memory map of the Tiva C Series device
#include "inc/hw_types.h"               // Defines common types and macros
#include "driverlib/sysctl.h"           // Defines and macros for System Control API of DriverLib
#include "driverlib/gpio.h"             // Defines and macros for GPIO API of DriverLib

/* -----------------------      Global Variables        --------------------- */

uint8_t ui8PinData = 0x02;              // Variable to store the pin data of GPIO PortF

/* -----------------------          Main Program        --------------------- */
int main(void){
    // Set the System clock to 80MHz and enable the clock for peripheral GPIOF
    SysCtlClockSet(SYSCTL_SYSDIV_2_5 | SYSCTL_USE_PLL | SYSCTL_XTAL_16MHZ | SYSCTL_OSC_MAIN);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);

    // Configure the PF1, PF2 and PF3 ports as Digital Output Pins
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3);

    while (true){
        // Write the output value to the GPIO PortF to control the PF1, PF2 and PF3
        GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3 | GPIO_PIN_2 | GPIO_PIN_1, ui8PinData);
        // Create a delay by wasting machine cycles in a loop
        SysCtlDelay(26666667);
        // Clear the Output of the GPIO PortF for PF1, PF2 and PF3
        GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3 | GPIO_PIN_2 | GPIO_PIN_1, 0x00);
        SysCtlDelay(26666667);

        // If the PF3 port was activated, restart the cycle by outputting to PF1
        if (ui8PinData == GPIO_PIN_3){
            ui8PinData = GPIO_PIN_1;
        } else
            // else Left Shift the ui8PinData to output to the next pin
            ui8PinData = ui8PinData << 1;
    }
}
